config/initializers/carrierwave.rb
config/secrets.yml

Sets geocoding and AWS S3 env variables. 
Closes #7

Configure geocoding and AWS

---

config/initializers/decidim.rb

Missing configuration for Decidim. Related to #14.

Configure Decidim

---

Gemfile
Gemfile.lock
app.json
config/initializers/carrierwave.rb
config/initializers/decidim.rb
db/seeds.rb

Add review apps

---

Gemfile
Gemfile.lock
app/controllers/decidim_controller.rb
config/environments/production.rb
config/secrets.yml

Add missing Heroku addons.
Closes #7

Add Heroku dependencies

---

Gemfile
Gemfile.lock
Procfile
config/environments/production.rb
config/routes.rb

Adds passenger as server and sidekiq as background jobs manager. 
Fixes #8 and #21.

Add sidekiq and passenger

---

config/sidekiq.yml

Add missing sidekiq config
- Related to #23 
None

Add sidekiq config

---

config/locales/ca.yml
config/locales/es.yml

Since it could confuse users, use "City" instead of "Global scope". Also, the scopes here are "Barris"

Change the global scope name

---

app.json
config/initializers/decidim.rb

This adds a custom method to calculate references using the resource id.
The references must be deleted in order to recalculate the new ones.
- Closes #40 
None
None

Add custom method to calculate references

---

Gemfile
Gemfile.lock
app/views/census_authorization/_form.html.erb
app/views/layouts/decidim/_head_extra.html.erb
bin/rspec

Use datepicker on census authorization form.
None

Use datepicker on census

---

app/views/census_authorization/_form.html.erb

Replaces the datepicker with a select.
- Fixes #52.

Use date select on census form

---

spec/factories.rb
spec/features/authorizations_spec.rb
spec/rails_helper.rb

Add tests for authorizations feature.

Add tests for authorizations

---

Gemfile
Gemfile.lock
app/services/census_authorization_handler.rb

This adds virtus multiparams in order to correctly coerce census data in the admin.
*None*
*None*
*None*
*None*

Add virtus multiparams in census authorization

---

.circleci/config.yml

Remove unneeded CircleCI steps

Remove unneeded CircleCI steps

---

.circleci/config.yml
Gemfile
Gemfile.lock
db/migrate/20200603101239_create_decidim_term_customizer_translation_sets.decidim_term_customizer.rb
db/migrate/20200603101240_create_decidim_term_customizer_translations.decidim_term_customizer.rb
db/migrate/20200603101241_create_decidim_term_customizer_constraints.decidim_term_customizer.rb
db/schema.rb

Add the term-customizer module to staging
- None
None

Add term customizer module

---

Gemfile
Gemfile.lock
app/lib/decidim/overwrites/calendar.rb
config/initializers/decidim.rb

Adds `decidim-term_customizer` gem and fixes a conflict with `decidim-calendar`

Add decidim-term_customizer

---

Gemfile
Gemfile.lock
db/migrate/20201119110444_create_decidim_term_customizer_translation_sets.decidim_term_customizer.rb
db/migrate/20201119110445_create_decidim_term_customizer_translations.decidim_term_customizer.rb
db/migrate/20201119110446_create_decidim_term_customizer_constraints.decidim_term_customizer.rb
db/schema.rb

Adds `term_customizer` module.
- Related to [Add customizer](https://app.clickup.com/t/agu2g9)

Add term customizer

---

Gemfile.lock

This PR updates staging to the latest Decidim version.

Update staging to latest Decidim

---

config/secrets.yml

This PR adds the SMTP Port as an env var, to simplify the overwritting

Add SMTP port as env var

---

config/environments/production.rb
config/storage.yml

This PR enables Amazon storage

Configure amazon storage

---

Gemfile
Gemfile.lock
config/initializers/aws_sdk_service.rb
lib/active_storage/client_service_initialization_overrides.rb

Add missing S3 initializer for AS

Add S3 initializer

---

config/sidekiq.yml

This PR updates sidekiq queues

Update sidekiq queues

---

.github/workflows/deploy_production.yml
.github/workflows/deploy_staging.yml
app.json

This PR prepares the production site for Dokku environment.

Setup deploy with dokku

---

Aptfile

This PR adds Aptfile configuration file to be used by apt buildpack

Add Aptfile
